name: Deploy to Azure Web App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build application
      run: npm run build --if-present
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'app-cialix-automation-test-prod-001'
        publish-profile: |
          <publishData><publishProfile profileName="app-cialix-automation-test-prod-001 - Web Deploy" publishMethod="MSDeploy" publishUrl="app-cialix-automation-test-prod-001.scm.azurewebsites.net:443" msdeploySite="app-cialix-automation-test-prod-001" userName="$app-cialix-automation-test-prod-001" userPWD="pxBsL6fz0EyqfQM8kk1JzhTFt1p2hblJeNzqeq4fyfeBaJpPJL7ybRATbXGA" destinationAppUrl="http://app-cialix-automation-test-prod-001.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="app-cialix-automation-test-prod-001 - FTP" publishMethod="FTP" publishUrl="ftps://waws-prod-mwh-119.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="app-cialix-automation-test-prod-001\$app-cialix-automation-test-prod-001" userPWD="pxBsL6fz0EyqfQM8kk1JzhTFt1p2hblJeNzqeq4fyfeBaJpPJL7ybRATbXGA" destinationAppUrl="http://app-cialix-automation-test-prod-001.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="app-cialix-automation-test-prod-001 - Zip Deploy" publishMethod="ZipDeploy" publishUrl="app-cialix-automation-test-prod-001.scm.azurewebsites.net:443" userName="$app-cialix-automation-test-prod-001" userPWD="pxBsL6fz0EyqfQM8kk1JzhTFt1p2hblJeNzqeq4fyfeBaJpPJL7ybRATbXGA" destinationAppUrl="http://app-cialix-automation-test-prod-001.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>

        package: .
